### ISSUE TITLE
Request to join a team

### ISSUE THREAD

**Issue by zarino** [mysociety/neighbourhood-warmth#15]
- User model
- Signup form: name, email, option to receive tips by email
- Confirm which details will be shared with existing team members
- Confirmation email
- Send “a neighbour has requested to join” email to other members of the team

**Comment by zarino** [comment]
@sequencefree Sorry the email preview links in the staging site are broken – I never quite finished switching them over from the old street-based link format to the team-based one.

But you can see source code for the emails here:

https://github.com/mysociety/neighbourhood-warmth/blob/572ad4b5d10c4e9c394c7d2377beed9fd4e335bf/neighbourhood/templates/neighbourhood/email_joined.html

https://github.com/mysociety/neighbourhood-warmth/blob/572ad4b5d10c4e9c394c7d2377beed9fd4e335bf/neighbourhood/templates/neighbourhood/email_welcome.html

Pretty minimal at the moment!

As mentioned above, I think we’ll want to re-word these around "Requested to join", and "Request has been approved".

**Comment by sequencefree** [comment]
@zarino I've drafted 3 x short emails in [this bit of our web copy document](https://docs.google.com/document/d/1O9FsQXOTPiRDl2daBdF-WJlaS7Un7W0lr-2DEv5-vyw/edit#heading=h.95mj1stpmyz) to cover:

1. Invitation to join a team
2. Request approved
3. Request rejected

Anything else you can think of that I could do on this one? Shall I flesh out the copy immediately above these draft emails under the heading **TEAM PAGE (no members, anonymous user viewing)**?

**Comment by zarino** [comment]
> Shall I flesh out the copy immediately above these draft emails under the heading TEAM PAGE (no members, anonymous user viewing)?

Yeah, you could do! Right now, [this is all that’s displayed to non-members users on the team page](https://github.com/mysociety/neighbourhood-warmth/blob/bab65f9df99b0fe286771aabb5d3edd5b77f40b7/neighbourhood/templates/neighbourhood/includes/generic_promo.html):

<img width="751" alt="Screenshot 2023-06-02 at 14 00 17" src="https://github.com/mysociety/neighbourhood-warmth/assets/739624/cbb30743-2106-40f0-9b52-fed22ef86d60">

(It’s the same text we display on the homepage.)
