### ISSUE TITLE
Show summary info on team page

### ISSUE THREAD

**Issue by zarino** [mysociety/neighbourhood-warmth#16]
**Public info**

- [x] Team’s rough location
- [x] Number of people signed up to the team
- [x] Team’s current status (looking for members, etc)
- [x] Generic content encouraging visitors to join team

**Team members only**

- [x] Detailed description of current step
- [x] Indication of past and future steps (to show progress)
- [x] Social sharing / invite links

Need to make it clear which part of the page is visible only because the user is already a member, so people understand what _they_ can see on the page is different to what _the public_ will see when they search / are given a link.

**Team admins only**

- [x] "Open to join requests" control
- [ ] (non-functional for now) controls to remove members, promote/demote admins

**Comment by sequencefree** [comment]
@zarino Please could you sense check below?

Thinking we have different versions of the team page depending on the status of the user viewing them (and the team's progress through the steps).

This is the view for non-team members https://neighbourhood-warmth.staging.mysociety.org/team/halton-park-heroes-100003/

This is the view for first member after creating the team: https://neighbourhood-warmth.staging.mysociety.org/team/halton-park-heroes-100003/?mine=1&congrats=1#

Would be good to create a view that the team's second (and maybe subsequent) members would see, which I think combines the headline information visible to non-members that you've outlined above with the accordion updated to hide step 2 and show step 3.

If that sounds sensible, shall I create a separate ticket or just add copy for step 3 in another comment below?

Ta!

**Comment by zarino** [comment]
@sequencefree I’ve updated the comment above – what do you think?

**Comment by sequencefree** [comment]
> @sequencefree I’ve updated the comment above – what do you think?

Looks good thanks @zarino esp. additional point on clarifying visibility based on membership. Ta!
