### ISSUE TITLE
Create new team

### ISSUE THREAD

**Issue by struan** [mysociety/neighbourhood-warmth#27]
Add a new team with name, email contact and location.

TBD: if there are any rules about when you can create a team

**Comment by sequencefree** [comment]
I think the **Your address** field in the **Your personal account** form also needs a **This won’t be shared with anyone** label beneath it.

**Comment by sequencefree** [comment]
@zarino Figure this is where we need to get users' consent as described in [this section of Neighbourhood Warmth Alpha data protection impact assessment](https://docs.google.com/document/d/152H-vH2ip8zWIxxScj2eShfspVFZFLDvc3yhR-6Erzw/edit#heading=h.u6uhkg9j571j) so haven't created a separate ticket.
