### ISSUE TITLE
Ad hoc stakeholder engagement for Neighbourhood Warmth Alpha stage

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/neighbourhood-warmth#4]
**Next steps**

- [ ] @sequencefree to explore possibility of demonstrating Alpha to retrofit services providers bilaterally.

**Background**

Included in [Neighbourhood Warmth Project Outline #1](https://github.com/mysociety/neighbourhood-warmth/issues/1)

Depends on [Cement partnership with an organisation#2](https://github.com/mysociety/neighbourhood-warmth/issues/2)

Separate ticket for setting up stakeholder group who can help us shape NW.

https://www.mysociety.org/tag/neighbourhood-warmth/

**Comment by sequencefree** [comment]
- [ ] Danielle Gregory (Tower Blocks UK)
- [ ] Sara Edmonds (Architects Climate Action Network)
- [ ] Nikki Brain (Frome Town Council)
- [ ] Joanne Wheeler (UK Green Building Council)
- [ ] Marianne Heaslip (URBED / People Powered Retrofit)
- [ ] Cara Jenkinson (Ashden)
- [ ] Matt Copeland (National Energy Action)
- [ ] Dr Rebecca Willis (Lancaster University)
- [ ] Louise Marix Evans (Quantum Strategy)
- [ ] Jo Wall (Local Partnerships)
- [ ] Stephen Jones (Climate Northern Ireland)
- [ ] Marie Brousseau-Navarro (Office of the Future Generations Commissioner for Wales)
- [ ] George Tarvit (Sustainable Scotland Network)
- [ ] Keith Hempshall (Centre for Sustainable Energy)
- [ ] Dan Wilson Craw (Generation Rent)
- [ ] Fraser Stewart (Regen)
- [ ]

**Comment by sequencefree** [comment]
@sequencefree to share https://www.mysociety.org/2023/06/06/neighbourhood-warmth-monthnotes-month-1/ with stakeholders below:

- [ ] Heledd Morgan (Future Generations Commissioner's Office)
- [ ] Stephen Lorimer (Centre for Net Zero)
- [ ]  Dan Edelstyn (POWER)
- [ ]  Joe Ash & Lynne McDonald (UK Power Networks)
- [ ]  Danielle Gregory (Tower Blocks UK)
- [ ]  Brigitte Clements, James Rixon (Architects Climate Action Network)
- [ ]  Sara Edmonds (Home Energy Action Lab)
- [ ]  Marta Nowicka (Students Organising for Sustainability UK)
- [ ]  Nikki Brain, Joanna Morris & Jacob Hall (Frome Town Council & Mendip District Council)
- [ ]  Joanne Wheeler (UK Green Building Council)
- [ ]  Marianne Heaslip (People Powered Retrofit)
- [ ]  Cara Jenkinson (Ashden)
- [ ]  Matt Copeland (National Energy Action)
- [ ]  Dr Rebecca Willis (Lancaster University)
- [ ]  Louise Marix Evans (Quantum Strategy)
- [ ]  Gareth Harcombe, Alastair Chapman (Cardiff Council)
- [ ]  Jo Wall, Jane Forshaw (Local Partnerships)
- [ ]  Stephen Jones (Climate Northern Ireland)
- [ ]  Heledd Morgan, Marie Brousseau-Navarro (Office of the Future Generations Commissioner for Wales)
- [ ]  George Tarvit (Sustainable Scotland Network)
- [ ]  Keith Hempshall, Ian Preston (Centre for Sustainable Energy)
- [ ]  Dan Wilson Craw (Generation Rent)
- [ ]  Fraser Stewart (Regen)
- [ ]  Nicki Myers, Chris Rowland (Ovesco)
- [ ]  Ollie Pendered (Community Energy South)
- [ ]  Kate Coulthard (Newcastle City Council)
- [ ]  Laura McGadie (Energy Savings Trust)
- [ ]  Peter Rickaby (Rickaby Thompson Associates)
- [ ]  Nabil Al-Kinani (https://nabilalkinani.com/)
- [ ]  Robert Harwood (Slingshot Simulations)
- [ ]  Carbon Co-op
- [ ]  Jim Parker (Leeds Beckett University)
- [ ]  Sarah Forsey (Citizens UK)
- [ ]  Poppy Maltby (Head of Cities and Regions, Regen)
- [ ]  Dan Clarke, Head of Innovation (Energy Networks Association)
- [ ]  Stevie Adams, Project Manager (Scottish and Southern Energy Networks)
- [ ]  Josie Evetts, Project Manager (Parity Projects)
- [ ]  Mark Ross, Strategic Partnerships Manager (Retrofit Academy)
- [ ]  See longer list.

**Comment by sequencefree** [comment]
If NLCF bid successful we'll set up a steering group with project partners, otherwise engagement will happen via other tickets on monthnotes and funding bids, and Siôn will fold stakeholders listed here into [Climate stakeholders](https://docs.google.com/spreadsheets/d/1MF5Bo9CaMFYDFlBugA9dwyxgRyHV9lOqCMggByQEuUY/edit?usp=sharing) spreadsheet as part of handover.
