### ISSUE TITLE
Allow team admins to approve/reject requests to join the team, and email applicant on decision

### ISSUE THREAD

**Issue by zarino** [mysociety/neighbourhood-warmth#45]
The three outstanding tasks from #39:

- [x] Send email to team organiser(s), to notify join request has been received
- [x] "Requests to join your team" page, for organiser(s) to approve/reject requests
- [x] Send approved/rejected email to requestor

**Comment by zarino** [comment]
@struan – See below wording for the emails, from @sequencefree.

We’ll need to think how this gets split between email and webpage (we probably don’t want a form submission inside the admin email markup, for example).

### Email to admin

> Congratulations!
> 
> [ NAME ] has requested to join your team.
> 
> [ checkbox ] Allow this person to approve/reject join requests from other people from now on.
> 
> [ Button: Approve member ]   [ Button: Reject request ]
> 
> Thanks!
> 
> Neighbourhood Warmth HQ
> 
> P.S. If you want to stop new member requests, please change the open/closed group setting on your team’s homepage: [ LINK ]

### Email to approved applicant

> Congratulations!
> 
> [ TEAM NAME ] has approved your request to join. [ IF USER.IS_ADMIN ] You have also been given permission to approve/reject requests from future applicants to this team. [ /IF ]
> 
> Visit your new team’s homepage to get involved in the next step on their current neighbourhood challenge:
> 
> [ TEAM URL ]
> 
> Thanks!
> 
> Neighbourhood Warmth HQ

I figure we’ll also want something for when a request has been rejected, perhaps:

### Email to rejected applicant

> Unfortunately your request to join [ TEAM NAME ] has been rejected. Perhaps the team already has all the members they need, or maybe they’re winding down.
> 
> Don’t let this stop you! Search for your local area by postcode, and see whether there are other teams you could join (or start for yourself!) nearby:
> 
> [ URL ]
> 
> All the best,
> 
> Neighbourhood Warmth HQ

**Comment by sequencefree** [comment]
Point made by an external I talked this through with earlier – approver need to be able to tailor the email (or the team homepage) to let the new member know how to communicate with other team members?

Sorry if this is already covered, just sharing quickly before battery dies.
