### ISSUE TITLE
Prep a one-pager (or a very short slide deck) about Neighbourhood Warmth

### ISSUE THREAD

**Issue by zarino** [mysociety/neighbourhood-warmth#75]
**Next steps**

- [x] @sequencefree to draft [Neighbourhood Warmth pitch deck](https://docs.google.com/presentation/d/1RwtTO8BCXVX8NufTchadahKlpyN_JPcPyVORulzHc1g/edit?usp=sharing) and request @zarino's feedback.
- [x] @zarino to provide feedback.
- [x] @sequencefree to finalise and share with Dan Hyde.

**Background**

As we’re talking to more people about our plans for Neighbourhood Warmth, a couple have asked if we have a short description of the whole thing that we can send to them, for them to share with colleagues / contacts.

This could potentially be a written document, but I wonder whether a slide deck might be punchier? Could even borrow from the commercial world and use one of the classic [10(ish) point VC pitch decks](https://www.masterclass.com/articles/pitch-deck-guide).

**Comment by sequencefree** [comment]
@zarino Belatedly pulled this into current sprint as I think this could be a useful complement to the [🏠 Neighbourhood Warmth brief for potential partners_NLCF Climate and Energy Fund_Nov 2023](https://docs.google.com/document/d/1UrmWrZ0KbJSlv8Wu03Zu0GskkCCUnPT1XEqf4juY2bY/edit?usp=sharing) to share with potential partners.

I'm going to read the article you've shared above and then happy to try and draft one, leave to you or collaborate on it – any preference?

**Comment by zarino** [comment]
@sequencefree We can work on it together! Or you can have a first stab, and then I can take a look. Whatever you’d prefer!
